name: Nuget Test

on:  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'jellyfin/jellyfin'
      
      - run: nuget config -Set maxHttpRequestsPerSource=1

      - run: dotnet restore Jellyfin.sln --verbosity detailed --force
